### ISSUE TITLE
Cannot connect via raspberrypi 4

### ISSUE THREAD

**Issue by jmitterh** [sidit77/InputShareUSB#2]
Followed instructions:

- Downloaded client to desktop and connected raspberrypi to laptop under same ethernet network. 
- Configured config.txt and modules (then I rebooted) to power up raspberrypi as a usb when connected via my laptop.
- Downloaded server-side inputshare-server (inputshare-server-armv7-unknown-linux-gnueabihf.tar.gz), unzipped and did the sudo command to start the server.

-When I attempted to connect via client desktop connection it would time out. I left the json file as default.
-using wireless usb connection for mouse and keyboard.

The only error is: Disconnected:TimedOut from the desktop client side.

Here is rasbperrypi 4 with process running:
![putty](https://user-images.githubusercontent.com/23060364/148715087-d164ffc6-ac88-49fa-b5eb-3411d0cc0418.PNG)

**Comment by sidit77** [comment]
Your screenshots seems to imply that you are using `USBraspberrypi` as hostname instead of the default `raspberrypi.local`. Have you edited the json file to reflect this?

Basically when you press *Connect* the client will start sending `ConnectionRequest` packets to the host from that file. The server will answer these packets with `ConnectionAccepted`. However if the client does not get one of these `ConnectionAccepted` packets within 5s it will throw the `Disconnected:TimedOut` error.

Can you ping (`ping USBraspberrypi`) your raspberry?

Also you should always use the same version of server and client. The master branch has a change that causes the both server and client to ignore all packets from previous versions.

**Comment by jmitterh** [comment]
You're absolutely right. So obvious but didn't realize it. Thank you for the quick response and this awesome app you created.
