### ISSUE TITLE
Error when starting control

### ISSUE THREAD

**Issue by sharkoz** [sidit77/InputShareUSB#3]
Hello,

I have a weird bug that started preventing me from using the tool.
It was working perfectly, then out of the blue I started having problems.

The scenario is : 
I can start the server
I can start the client, and connect
As soon as I hit the hotkey to switch the mouse and keyboard to the rPi, the server and the client crash

Here is what I see on the rPi :
```
>sudo ./inputshare-server
Enabling HID device
Opening HID devices
Started server on 0.0.0.0:60067
```

When I connect the main PC, I get on stdout :
`Client 0 connected`
So far so good

But when I switch the controls to the Pi, it crashes :
```
Disabling HID device
Error: Cannot send after transport endpoint shutdown (os error 108)
>
```

And on the local PC, I get the error "os error 10054"

Is there anything I can try to fix it ?

**Comment by sidit77** [comment]
> And on the local PC, I get the error "os error 10054"

I think this simply means that the server unexpectantly disappeared.

Unfortunately I can only guess why and where the server crashes because logging is currently pretty much non-existent. I plan on fixing this the next time I work on this project but I don't know yet when that will be as I currently somewhat busy.

So here is what I think happens:
When you start the server it uses configfs to create three virtual USB devices: `/dev/hidg0` (Keyboard), `/dev/hidg1` (Mouse), `/dev/hidg2` (Media keys). Next it will attempt to open these devices in write mode but not yet write to them. The write happens when the server either receives a new command (Mouse move or key press / release) or a client disconnects. And I think this write is what ends up causing the crash because something corrupted at least one of the devices.
My best idea to confirm if this is really the case would be to manually write into one of the devices:
`sudo echo -ne '\x00\x00\x04\x00\x00\x00\x00\x00' > /dev/hidg0` should press the A-key and
`sudo echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0` should release it again.

**Comment by sharkoz** [comment]
Hi,

Thanks for your answer.

I tried what you said and it replies the same error message :

```
root@DietPi:~# sudo echo -ne '\x00\x00\x04\x00\x00\x00\x00\x00' > /dev/hidg0
echo: write error: Cannot send after transport endpoint shutdown
```

But with the echo the server does not crash.

As you said, disconnecting from the client also causes the crash.

I checked, and when the server is off the devices disappear from /dev
What I realised, is that when you told me about the /dev/hidg* I checked and although the server was down, I still had a `/dev/hidg0` file present. I manually deleted it with rm, and now the devices disappear when the server is down, and reappear when it is up. But it still doesn't work

I don't know much about how these virtual devices work, but if there is anything else I can do to help debugging, I'll try it.

Thanks

**Comment by sidit77** [comment]
> But with the echo the server does not crash.

Yeah because the server is not executing the command. 
Interestingly enough when I try to run the command I get `-bash: /dev/hidg0: Permission denied`. I guess this is because the server already has to file opened. If you get to this part I could send you a modified binary with nothing but the hid device setup code.

> I checked, and when the server is off the devices disappear from /dev

Yeah, this is the intended behavior. The program tries the best to clean up after itself. This is also where the `Disabling HID device` line comes from.

The problem now is that I don't think that the problem is on "my" end as even the raw bash command has this issue. I honestly don't know what would cause this. Could be anything from faulty software to hardware. If you have a second sd card I would just try a fresh OS install to see if this is a software problem.

**Comment by sharkoz** [comment]
Hello,
And thanks for your feedback.
A full reinstall of the OS on another SD card fixed the problem for now !
I hope it'll keep working that way ;)

**Comment by sidit77** [comment]
Great to hear
