### ISSUE TITLE
Cannot send after transport endpoint shutdown (os error 108)

### ISSUE THREAD

**Issue by adaladdin** [sidit77/InputShareUSB#4]
I installed Raspbian OS Lite 32bit on a pizero, configured the dtoverlay and other settings as directed to set it as a libcomposite device, ran chmod on the compiled binary for the inputshare-server and everything is fine so far. Client is connecting to the server just fine as well, however as soon as i switch the client to Remote, and perform any action from either mouse or keyboard, it disconnects and i receive the following:

![image](https://user-images.githubusercontent.com/110638825/198407708-db679468-974c-4184-a46e-a8a8af8dcb35.png)

I did look at the issue opened by [sharkoz](https://github.com/sidit77/InputShareUSB/issues?q=is%3Aissue+author%3Asharkoz) and I did use completely different SD card and re-installed everything from scratch (numerous times), i also used the regular full desktop image instead of raspbian but nothing seems to work.

I do see the /dev/hidg0 and /dev/hidg1 and /dev/hidg2 created in the dev folder when the server is started, not sure what's going on.

I am connecting the raspberry pi using a micro usb cable into the port that is on the inner side (labeled USB).

Do I perhaps need to use an OTG micro USB cable? If so what would you recommend? I was under the impression that I didn't need to do that.

Any ideas?

**Comment by sidit77** [comment]
I don't think you need a special cable. I just connect my raspi to my laptop using a normal 20cm (male) USB to (male) Micro USB. Have you tried different cables? Maybe you could also try to plug you raspi into a different pc to see if that helps.

It's pretty hard to tell why this issue occurs because the whole USB device stuff is a bit of a black box and I generally just followed a tutorial to get it running.
Sorry that I can't  be more helpful in that regard. I'm sort of planning to see if I can port to server to the Raspberry Pico W once Rust support for the WIFI module is stable to cut down on these black boxes.

**Comment by adaladdin** [comment]
Figured out the issue... turns out it was the micro USB cable I was using.

I must have used about 10 different pairs that I had around the house and seems like not a single one of them was a valid data cable.

I gave up and purchased a new one from amazon, this one specifically: https://www.amazon.com/dp/B01JPEKJYI?psc=1&ref=ppx_yo2ov_dt_b_product_details

and it worked INSTANTLY with this cable.

Perhaps you can add some kind of a note in the instructions to "make sure you are using a good quality micro USB cable" or something of the sort. You can even link the one i just posted from amazon if you wish.
